# fly.toml app configuration file generated for proxy-ipv6 on 2024-06-17T12:18:23-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'proxy-ipv6'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
